grafana:
 restart: always
 image: grafana/grafana
 container_name: grafana
 ports:
  - "3000:3000"
 environment:
 - GF_SERVER_ROOT_URL=http://grafana.server.name
 - GF_SECURITY_ADMIN_PASSWORD=secret

graphite:
 restart: always
 image: hopsoft/graphite-statsd
 container_name: graphite
 ports:
  - "80:80"
  - "2003:2003"
  - "8125:8125/udp"
  - "8126:8126"


hub:
 restart: always
 image: selenium/hub:2.48.2
 container_name: selenium-hub
 ports:
  - "4444:4444"
firefox:
 image: selenium/node-firefox-debug:2.48.2
 ports:
  - "5900"
 links:
  - hub
chrome:
 image: selenium/node-chrome-debug:2.48.2
 ports:
  - "5900"
 links:
  - hub
