hub:
 restart: always
 image: selenium/hub:2.48.2
 container_name: selenium-hub
 ports:
  - "4444:4444"
firefox:
 image: selenium/node-firefox-debug:2.48.2
 ports:
  - "5900"
 links:
  - hub
chrome:
 image: selenium/node-chrome-debug:2.48.2
 ports:
  - "5900"
 links:
  - hub
